services:
  hr_governance:
    build: ./governance/hr_bot
    restart: always
    volumes:
      - ./data:/app/data

  strategist_governance:
    build: ./governance/ai_strategist
    restart: always
    volumes:
      - ./data:/app/data

  scale_governance:
    build: ./governance/auto_scale
    restart: always
    volumes:
      - ./data:/app/data

  lab_governance:
    build: ./governance/lab_bot
    restart: always
    volumes:
      - ./data:/app/data
audit_governance:
  build: ./governance/audit_bot
  restart: always
  volumes:
    - ./data:/app/data
health_score_governance:
  build: ./governance/health_score
  restart: always
  volumes:
    - ./data:/app/data
kill_switch_governance:
  build: ./governance/kill_switch
  restart: always
  volumes:
    - ./data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
    rollback_governance:
  build: ./governance/rollback
  restart: always
  volumes:
    - ./data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock

