version: "3.9"

services:
  fbim:
    build: .
    container_name: fbim-tech
    restart: always
    env_file: .env

    volumes:
      - ./secure/cookies:/secure/cookies
      - ./data:/app/data

    mem_limit: 10g
    cpus: "6.0"
